spring:
  application:
    name: movie-service  zipkin:    base-url: http://localhost:9411
    sender:      type: web
  sleuth:    sampler:      probability: 1

server:
  port: 8070

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:        defaultZone: http://localhost:8090/eureka
